server:
  port: 8888

eureka:
  instance:
    hostname: config-server
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:yangzijing/config.git
          search-paths: '{application}'
          #username: yourusername
          #password: yourpassword
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: config-server
