server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

#log4j:
#  rootLogger: info,ServerDailyRollingFile,stdout
#  appender:
#    ServerDailyRollingFile: org.apache.log4j.DailyRollingFileAppender
#      DatePattern: '.'yyyy-MM-dd#
#      File: test.log
#      layout: org.apache.log4j.PatternLayout
#        ConversionPattern: %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p [%c] - %m%n
#      Append: true
#    stdout: org.apache.log4j.ConsoleAppender
#      layout: org.apache.log4j.PatternLayout
#        ConversionPattern: %d yyyy-MM-dd HH:mm:ss %p [%c] %m%n