server:
  port: 8080

eureka:
  instance:
    hostname: zuul-gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: true
