server:
  port: 8080

eureka:
  instance:
    hostname: zuul-gateway
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: zuul-gateway

zuul:
  routes:
    OAuth2-server:
      path: /oauth2-server/**
      sensitiveHeaders:
      serviceId: oauth2-server

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/oauth2-server/oauth/token
      user-authorization-uri: http://localhost:8080/oauth2-server/oauth/authorize
      client-id: webapp
      client-secret: 12345678
    resource:
      user-info-uri: http://localhost:8080/oauth2-server/user
      prefer-token-info: false

management:
  security:
    enabled: false
