server:
  port: 8080

eureka:
  instance:
    hostname: zuul-gateway
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: zuul-gateway
