server:
  port: 8761

eureka:
  environment: EnvironmentName
  datacenter: CenterName
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
