spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  environment: EnvironmentName
  datacenter: CenterName
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true

